language: go
go:
  - "1.10"
go_import_path: github.com/carolynvs/az-cli
sudo: required
services:
  - docker
script: make build-all
deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "bin/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true